---
- name: Install Firewall for both Ubuntu and CentOS
  hosts: all
  become: yes
  tasks:
    - name: Install Firewalld
      ansible.builtin.yum:
        name: firewalld
        state: present
      when: ansible_distribution == 'CentOS'

    - name: Installing UFW
      ansible.builtin.apt:
        name: ufw
        state: present
      when: ansible_distribution == 'Ubuntu'

- name: Enable Firewall for both Ubuntu and CentOS
  hosts: all
  become: yes
  tasks:
    - name: Enabling Firewalld
      ansible.builtin.service:
        name: firewalld
        state: started
        enabled: yes
      when: ansible_distribution == 'CentOS'

    - name: Enabling UFW
      ansible.builtin.service:
        name: ufw
        state: started
        enabled: yes
      when: ansible_distribution == 'Ubuntu'

- name: Allowing ports (SSH, Http, Https)for both Ubuntu and CentOS
  hosts: all
  become: yes
  tasks:

    - name: Allowing additional ports through firewall
      ansible.builtin.firewalld:
        port: "{{ item }}"
        permanent: yes
        state: enabled
      loop:
        - 22/tcp
        - 80/tcp
        - 443/tcp
      when: ansible_distribution == 'CentOS'

    - name: Allow additional ports through firewall
      ansible.builtin.ufw:
        rule: allow
        port: "{{ item }}"
        proto: tcp
      loop:
        - 22
        - 80
        - 443
      when: ansible_distribution == 'Ubuntu'


